//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenStore.Omnichannel.Panel.Resources.Pages.Products {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Create_tr_TR {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Create_tr_TR() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("OpenStore.Omnichannel.Panel.Resources.Pages.Products.Create_tr_TR", typeof(Create_tr_TR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Button_Save {
            get {
                return ResourceManager.GetString("Button.Save", resourceCulture);
            }
        }
        
        internal static string NewProduct {
            get {
                return ResourceManager.GetString("NewProduct", resourceCulture);
            }
        }
        
        internal static string Breadcrumb_Products {
            get {
                return ResourceManager.GetString("Breadcrumb.Products", resourceCulture);
            }
        }
        
        internal static string Breadcrumb_AddProduct {
            get {
                return ResourceManager.GetString("Breadcrumb.AddProduct", resourceCulture);
            }
        }
        
        internal static string CardTitle_Media {
            get {
                return ResourceManager.GetString("CardTitle.Media", resourceCulture);
            }
        }
        
        internal static string CardTitle_Pricing {
            get {
                return ResourceManager.GetString("CardTitle.Pricing", resourceCulture);
            }
        }
        
        internal static string CardTitle_Inventory {
            get {
                return ResourceManager.GetString("CardTitle.Inventory", resourceCulture);
            }
        }
        
        internal static string CardTitle_Shipping {
            get {
                return ResourceManager.GetString("CardTitle.Shipping", resourceCulture);
            }
        }
        
        internal static string CardTitle_Variants {
            get {
                return ResourceManager.GetString("CardTitle.Variants", resourceCulture);
            }
        }
        
        internal static string CardTitle_Seo {
            get {
                return ResourceManager.GetString("CardTitle.Seo", resourceCulture);
            }
        }
        
        internal static string CardTitle_Tags {
            get {
                return ResourceManager.GetString("CardTitle.Tags", resourceCulture);
            }
        }
        
        internal static string CardTitle_Collections {
            get {
                return ResourceManager.GetString("CardTitle.Collections", resourceCulture);
            }
        }
        
        internal static string CardTitle_Status {
            get {
                return ResourceManager.GetString("CardTitle.Status", resourceCulture);
            }
        }
        
        internal static string CardTitle_Channels {
            get {
                return ResourceManager.GetString("CardTitle.Channels", resourceCulture);
            }
        }
    }
}
