//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenStore.Omnichannel.Panel.Resources.Pages.Products {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Index_tr_TR {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index_tr_TR() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("OpenStore.Omnichannel.Panel.Resources.Pages.Products.Index_tr_TR", typeof(Index_tr_TR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Breadcrumb_Home {
            get {
                return ResourceManager.GetString("Breadcrumb.Home", resourceCulture);
            }
        }
        
        internal static string Breadcrumb_ProductList {
            get {
                return ResourceManager.GetString("Breadcrumb.ProductList", resourceCulture);
            }
        }
        
        internal static string AddProduct {
            get {
                return ResourceManager.GetString("AddProduct", resourceCulture);
            }
        }
        
        internal static string ProductList_InventoryColumn {
            get {
                return ResourceManager.GetString("ProductList.InventoryColumn", resourceCulture);
            }
        }
        
        internal static string ProductList_InventoryNotTracking {
            get {
                return ResourceManager.GetString("ProductList.InventoryNotTracking", resourceCulture);
            }
        }
        
        internal static string ProductList_PhysicalProduct {
            get {
                return ResourceManager.GetString("ProductList.PhysicalProduct", resourceCulture);
            }
        }
        
        internal static string ProductList_NonPhysicalProduct {
            get {
                return ResourceManager.GetString("ProductList.NonPhysicalProduct", resourceCulture);
            }
        }
        
        internal static string ColumnHeader_Title {
            get {
                return ResourceManager.GetString("ColumnHeader.Title", resourceCulture);
            }
        }
        
        internal static string ColumnHeader_Inventory {
            get {
                return ResourceManager.GetString("ColumnHeader.Inventory", resourceCulture);
            }
        }
        
        internal static string ColumnHeader_Category {
            get {
                return ResourceManager.GetString("ColumnHeader.Category", resourceCulture);
            }
        }
        
        internal static string ColumnHeader_Type {
            get {
                return ResourceManager.GetString("ColumnHeader.Type", resourceCulture);
            }
        }
        
        internal static string ColumnHeader_Status {
            get {
                return ResourceManager.GetString("ColumnHeader.Status", resourceCulture);
            }
        }
        
        internal static string ProductListItem_Active {
            get {
                return ResourceManager.GetString("ProductListItem.Active", resourceCulture);
            }
        }
        
        internal static string ProductListItem_Draft {
            get {
                return ResourceManager.GetString("ProductListItem.Draft", resourceCulture);
            }
        }
        
        internal static string ProductListTab_All {
            get {
                return ResourceManager.GetString("ProductListTab.All", resourceCulture);
            }
        }
        
        internal static string ProductListTab_Active {
            get {
                return ResourceManager.GetString("ProductListTab.Active", resourceCulture);
            }
        }
        
        internal static string ProductListTab_Draft {
            get {
                return ResourceManager.GetString("ProductListTab.Draft", resourceCulture);
            }
        }
        
        internal static string ProductListTab_Archived {
            get {
                return ResourceManager.GetString("ProductListTab.Archived", resourceCulture);
            }
        }
    }
}
