//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenStore.Omnichannel.Panel.Resources.Pages.Products {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PricingEditor_tr_TR {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PricingEditor_tr_TR() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("OpenStore.Omnichannel.Panel.Resources.Pages.Products.PricingEditor_tr_TR", typeof(PricingEditor_tr_TR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Input_Price {
            get {
                return ResourceManager.GetString("Input.Price", resourceCulture);
            }
        }
        
        internal static string Input_ComparePrice {
            get {
                return ResourceManager.GetString("Input.ComparePrice", resourceCulture);
            }
        }
        
        internal static string Input_Cost {
            get {
                return ResourceManager.GetString("Input.Cost", resourceCulture);
            }
        }
        
        internal static string Input_Margin {
            get {
                return ResourceManager.GetString("Input.Margin", resourceCulture);
            }
        }
        
        internal static string Input_Profit {
            get {
                return ResourceManager.GetString("Input.Profit", resourceCulture);
            }
        }
        
        internal static string InputHelp_CustomerDontSeeThisInfo {
            get {
                return ResourceManager.GetString("InputHelp.CustomerDontSeeThisInfo", resourceCulture);
            }
        }
        
        internal static string Input_ChargeTaxOnTheVariant {
            get {
                return ResourceManager.GetString("Input.ChargeTaxOnTheVariant", resourceCulture);
            }
        }
    }
}
