//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenStore.Omnichannel.Panel.Resources.Pages.Products {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UpdateVariant_tr_TR {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UpdateVariant_tr_TR() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("OpenStore.Omnichannel.Panel.Resources.Pages.Products.UpdateVariant_tr_TR", typeof(UpdateVariant_tr_TR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Label_Draft {
            get {
                return ResourceManager.GetString("Label.Draft", resourceCulture);
            }
        }
        
        internal static string Label_Active {
            get {
                return ResourceManager.GetString("Label.Active", resourceCulture);
            }
        }
        
        internal static string Label_Archived {
            get {
                return ResourceManager.GetString("Label.Archived", resourceCulture);
            }
        }
        
        internal static string Label_Variants {
            get {
                return ResourceManager.GetString("Label.Variants", resourceCulture);
            }
        }
        
        internal static string Link_BackToProduct {
            get {
                return ResourceManager.GetString("Link.BackToProduct", resourceCulture);
            }
        }
        
        internal static string Title_Options {
            get {
                return ResourceManager.GetString("Title.Options", resourceCulture);
            }
        }
        
        internal static string CardHeader_Variants {
            get {
                return ResourceManager.GetString("CardHeader.Variants", resourceCulture);
            }
        }
        
        internal static string Button_SelectVariantImage {
            get {
                return ResourceManager.GetString("Button.SelectVariantImage", resourceCulture);
            }
        }
        
        internal static string Button_ChangeVariantImage {
            get {
                return ResourceManager.GetString("Button.ChangeVariantImage", resourceCulture);
            }
        }
    }
}
