//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenStore.Omnichannel.Panel.Resources.Pages.OnlineStore {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Preferences_tr_TR {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Preferences_tr_TR() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("OpenStore.Omnichannel.Panel.Resources.Pages.OnlineStore.Preferences_tr_TR", typeof(Preferences_tr_TR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Label_General {
            get {
                return ResourceManager.GetString("Label.General", resourceCulture);
            }
        }
        
        internal static string Label_General_P {
            get {
                return ResourceManager.GetString("Label.General.P", resourceCulture);
            }
        }
        
        internal static string Button_Edit {
            get {
                return ResourceManager.GetString("Button.Edit", resourceCulture);
            }
        }
        
        internal static string Label_StoreName {
            get {
                return ResourceManager.GetString("Label.StoreName", resourceCulture);
            }
        }
        
        internal static string Label_Contact {
            get {
                return ResourceManager.GetString("Label.Contact", resourceCulture);
            }
        }
        
        internal static string Label_Contact_P {
            get {
                return ResourceManager.GetString("Label.Contact.P", resourceCulture);
            }
        }
        
        internal static string Label_Email {
            get {
                return ResourceManager.GetString("Label.Email", resourceCulture);
            }
        }
        
        internal static string Label_Phone {
            get {
                return ResourceManager.GetString("Label.Phone", resourceCulture);
            }
        }
        
        internal static string Label_Address {
            get {
                return ResourceManager.GetString("Label.Address", resourceCulture);
            }
        }
        
        internal static string Label_CopyrightText {
            get {
                return ResourceManager.GetString("Label.CopyrightText", resourceCulture);
            }
        }
        
        internal static string Label_FacebookUrl {
            get {
                return ResourceManager.GetString("Label.FacebookUrl", resourceCulture);
            }
        }
        
        internal static string Label_InstagramUrl {
            get {
                return ResourceManager.GetString("Label.InstagramUrl", resourceCulture);
            }
        }
        
        internal static string Label_TwitterUrl {
            get {
                return ResourceManager.GetString("Label.TwitterUrl", resourceCulture);
            }
        }
        
        internal static string Label_YoutubeUrl {
            get {
                return ResourceManager.GetString("Label.YoutubeUrl", resourceCulture);
            }
        }
    }
}
