//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenStore.Omnichannel.Panel.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class App_tr_TR {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal App_tr_TR() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("OpenStore.Omnichannel.Panel.Resources.App_tr_TR", typeof(App_tr_TR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Validation_Required {
            get {
                return ResourceManager.GetString("Validation.Required", resourceCulture);
            }
        }
        
        internal static string Validation_Range {
            get {
                return ResourceManager.GetString("Validation.Range", resourceCulture);
            }
        }
        
        internal static string Success_Title {
            get {
                return ResourceManager.GetString("Success.Title", resourceCulture);
            }
        }
        
        internal static string Success_GenericCreated {
            get {
                return ResourceManager.GetString("Success.GenericCreated", resourceCulture);
            }
        }
        
        internal static string Error_Title {
            get {
                return ResourceManager.GetString("Error.Title", resourceCulture);
            }
        }
        
        internal static string Warning_Title {
            get {
                return ResourceManager.GetString("Warning.Title", resourceCulture);
            }
        }
        
        internal static string Warning_NotFound {
            get {
                return ResourceManager.GetString("Warning.NotFound", resourceCulture);
            }
        }
        
        internal static string Warning_Forbidden {
            get {
                return ResourceManager.GetString("Warning.Forbidden", resourceCulture);
            }
        }
        
        internal static string Domain_ProductHandleAlreadyExists {
            get {
                return ResourceManager.GetString("Domain.ProductHandleAlreadyExists", resourceCulture);
            }
        }
        
        internal static string Info_NoRecord {
            get {
                return ResourceManager.GetString("Info.NoRecord", resourceCulture);
            }
        }
        
        internal static string GenericSuccessMessage {
            get {
                return ResourceManager.GetString("GenericSuccessMessage", resourceCulture);
            }
        }
        
        internal static string GenericDeleteConfirm {
            get {
                return ResourceManager.GetString("GenericDeleteConfirm", resourceCulture);
            }
        }
        
        internal static string OpenStore_GenericError {
            get {
                return ResourceManager.GetString("OpenStore.GenericError", resourceCulture);
            }
        }
        
        internal static string ResourceNotFound {
            get {
                return ResourceManager.GetString("ResourceNotFound", resourceCulture);
            }
        }
        
        internal static string Generic_Cancel {
            get {
                return ResourceManager.GetString("Generic.Cancel", resourceCulture);
            }
        }
        
        internal static string Generic_Save {
            get {
                return ResourceManager.GetString("Generic.Save", resourceCulture);
            }
        }
        
        internal static string Generic_Delete {
            get {
                return ResourceManager.GetString("Generic.Delete", resourceCulture);
            }
        }
        
        internal static string Domain_MultipleVariantProductMustHasOptions {
            get {
                return ResourceManager.GetString("Domain.MultipleVariantProductMustHasOptions", resourceCulture);
            }
        }
        
        internal static string Domain_VariantAlreadyExistsThatHasSameOptions {
            get {
                return ResourceManager.GetString("Domain.VariantAlreadyExistsThatHasSameOptions", resourceCulture);
            }
        }
        
        internal static string Generic_Import {
            get {
                return ResourceManager.GetString("Generic.Import", resourceCulture);
            }
        }
        
        internal static string Generic_Export {
            get {
                return ResourceManager.GetString("Generic.Export", resourceCulture);
            }
        }
        
        internal static string Generic_All {
            get {
                return ResourceManager.GetString("Generic.All", resourceCulture);
            }
        }
    }
}
