//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenStore.Omnichannel.Panel.Resources.Pages.Inventory {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Index_tr_TR {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index_tr_TR() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("OpenStore.Omnichannel.Panel.Resources.Pages.Inventory.Index_tr_TR", typeof(Index_tr_TR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Breadcrumb_Inventory {
            get {
                return ResourceManager.GetString("Breadcrumb.Inventory", resourceCulture);
            }
        }
        
        internal static string ColumnHeader_Product {
            get {
                return ResourceManager.GetString("ColumnHeader.Product", resourceCulture);
            }
        }
        
        internal static string ColumnHeader_Sku {
            get {
                return ResourceManager.GetString("ColumnHeader.Sku", resourceCulture);
            }
        }
        
        internal static string ColumnHeader_WhenSoldOut {
            get {
                return ResourceManager.GetString("ColumnHeader.WhenSoldOut", resourceCulture);
            }
        }
        
        internal static string ColumnHeader_AvailableQuantity {
            get {
                return ResourceManager.GetString("ColumnHeader.AvailableQuantity", resourceCulture);
            }
        }
        
        internal static string ColumnHeader_EditQuantity {
            get {
                return ResourceManager.GetString("ColumnHeader.EditQuantity", resourceCulture);
            }
        }
        
        internal static string ContinueSelling {
            get {
                return ResourceManager.GetString("ContinueSelling", resourceCulture);
            }
        }
        
        internal static string StopSelling {
            get {
                return ResourceManager.GetString("StopSelling", resourceCulture);
            }
        }
    }
}
