//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenStore.Omnichannel.Panel.Resources.Pages.Products.Variant {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UpdateVariantsEditor_tr_TR {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UpdateVariantsEditor_tr_TR() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("OpenStore.Omnichannel.Panel.Resources.Pages.Products.Variant.UpdateVariantsEditor" +
                            "_tr_TR", typeof(UpdateVariantsEditor_tr_TR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        internal static string ListGroupItem_VariantQuantity {
            get {
                return ResourceManager.GetString("ListGroupItem.VariantQuantity", resourceCulture);
            }
        }
        
        internal static string ListGroupItem_TotalQuantity {
            get {
                return ResourceManager.GetString("ListGroupItem.TotalQuantity", resourceCulture);
            }
        }
        
        internal static string ListGroupItem_ShowingXVariants {
            get {
                return ResourceManager.GetString("ListGroupItem.ShowingXVariants", resourceCulture);
            }
        }
        
        internal static string Label_BulkSelect {
            get {
                return ResourceManager.GetString("Label.BulkSelect", resourceCulture);
            }
        }
        
        internal static string Button_AddVariant {
            get {
                return ResourceManager.GetString("Button.AddVariant", resourceCulture);
            }
        }
        
        internal static string Dropdown_BulkOperation {
            get {
                return ResourceManager.GetString("Dropdown.BulkOperation", resourceCulture);
            }
        }
        
        internal static string DropdownItem_BulkUpdatePrice {
            get {
                return ResourceManager.GetString("DropdownItem.BulkUpdatePrice", resourceCulture);
            }
        }
        
        internal static string DropdownItem_BulkUpdateStock {
            get {
                return ResourceManager.GetString("DropdownItem.BulkUpdateStock", resourceCulture);
            }
        }
        
        internal static string DropdownItem_BulkUpdateBarcode {
            get {
                return ResourceManager.GetString("DropdownItem.BulkUpdateBarcode", resourceCulture);
            }
        }
        
        internal static string UpdateVariantPricesModal_Title {
            get {
                return ResourceManager.GetString("UpdateVariantPricesModal.Title", resourceCulture);
            }
        }
        
        internal static string UpdateVariantPricesModal_Input_Price {
            get {
                return ResourceManager.GetString("UpdateVariantPricesModal.Input.Price", resourceCulture);
            }
        }
        
        internal static string UpdateVariantPricesModal_Input_CompareAtPrice {
            get {
                return ResourceManager.GetString("UpdateVariantPricesModal.Input.CompareAtPrice", resourceCulture);
            }
        }
        
        internal static string UpdateVariantPricesModal_Input_Cost {
            get {
                return ResourceManager.GetString("UpdateVariantPricesModal.Input.Cost", resourceCulture);
            }
        }
        
        internal static string UpdateVariantStocksModal_Title {
            get {
                return ResourceManager.GetString("UpdateVariantStocksModal.Title", resourceCulture);
            }
        }
        
        internal static string UpdateVariantStocksModal_Input_Quantity {
            get {
                return ResourceManager.GetString("UpdateVariantStocksModal.Input.Quantity", resourceCulture);
            }
        }
        
        internal static string UpdateVariantStocksModal_Input_Barcode {
            get {
                return ResourceManager.GetString("UpdateVariantStocksModal.Input.Barcode", resourceCulture);
            }
        }
        
        internal static string UpdateVariantBarcodesModal_Title {
            get {
                return ResourceManager.GetString("UpdateVariantBarcodesModal.Title", resourceCulture);
            }
        }
        
        internal static string DropdownItem_BulkUpdateSku {
            get {
                return ResourceManager.GetString("DropdownItem.BulkUpdateSku", resourceCulture);
            }
        }
        
        internal static string UpdateVariantSkusModal_Input_Sku {
            get {
                return ResourceManager.GetString("UpdateVariantSkusModal.Input.Sku", resourceCulture);
            }
        }
        
        internal static string UpdateVariantSkusModal_Title {
            get {
                return ResourceManager.GetString("UpdateVariantSkusModal.Title", resourceCulture);
            }
        }
        
        internal static string UpdateVariantCreateModal_Options {
            get {
                return ResourceManager.GetString("UpdateVariantCreateModal.Options", resourceCulture);
            }
        }
        
        internal static string UpdateVariantCreateModal_Title {
            get {
                return ResourceManager.GetString("UpdateVariantCreateModal.Title", resourceCulture);
            }
        }
        
        internal static string UpdateVariantPricesModal_PriceApplyAll {
            get {
                return ResourceManager.GetString("UpdateVariantPricesModal.PriceApplyAll", resourceCulture);
            }
        }
        
        internal static string UpdateVariantStocksModal_ApplyAll {
            get {
                return ResourceManager.GetString("UpdateVariantStocksModal.ApplyAll", resourceCulture);
            }
        }
        
        internal static string Label_ProductHasNoVariant {
            get {
                return ResourceManager.GetString("Label.ProductHasNoVariant", resourceCulture);
            }
        }
        
        internal static string HasMultipleVariants {
            get {
                return ResourceManager.GetString("HasMultipleVariants", resourceCulture);
            }
        }
        
        internal static string Button_SaveNewVariants {
            get {
                return ResourceManager.GetString("Button.SaveNewVariants", resourceCulture);
            }
        }
    }
}
