//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenStore.Omnichannel.Identity.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResource_tr_TR {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource_tr_TR() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("OpenStore.Omnichannel.Identity.Resources.SharedResource_tr_TR", typeof(SharedResource_tr_TR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Validation_Required {
            get {
                return ResourceManager.GetString("Validation.Required", resourceCulture);
            }
        }
        
        internal static string Validation_InvalidEmail {
            get {
                return ResourceManager.GetString("Validation.InvalidEmail", resourceCulture);
            }
        }
        
        internal static string Validation_PasswordMismatch {
            get {
                return ResourceManager.GetString("Validation.PasswordMismatch", resourceCulture);
            }
        }
        
        internal static string Validation_PasswordTooShort {
            get {
                return ResourceManager.GetString("Validation.PasswordTooShort", resourceCulture);
            }
        }
        
        internal static string Validation_DuplicateEmail {
            get {
                return ResourceManager.GetString("Validation.DuplicateEmail", resourceCulture);
            }
        }
        
        internal static string Validation_PasswordRequiresDigit {
            get {
                return ResourceManager.GetString("Validation.PasswordRequiresDigit", resourceCulture);
            }
        }
        
        internal static string Validation_PasswordRequiresLower {
            get {
                return ResourceManager.GetString("Validation.PasswordRequiresLower", resourceCulture);
            }
        }
        
        internal static string Validation_PasswordRequiresUpper {
            get {
                return ResourceManager.GetString("Validation.PasswordRequiresUpper", resourceCulture);
            }
        }
        
        internal static string Validation_PasswordRequiresUniqueChars {
            get {
                return ResourceManager.GetString("Validation.PasswordRequiresUniqueChars", resourceCulture);
            }
        }
        
        internal static string Validation_PasswordRequiresNonAlphanumeric {
            get {
                return ResourceManager.GetString("Validation.PasswordRequiresNonAlphanumeric", resourceCulture);
            }
        }
    }
}
