//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenStore.Omnichannel.Identity.Resources.Views.Account {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ForgotPassword_tr_TR {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ForgotPassword_tr_TR() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("OpenStore.Omnichannel.Identity.Resources.Views.Account.ForgotPassword_tr_TR", typeof(ForgotPassword_tr_TR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ForgotPassword_Email {
            get {
                return ResourceManager.GetString("ForgotPassword.Email", resourceCulture);
            }
        }
        
        internal static string ForgotPassword_Title {
            get {
                return ResourceManager.GetString("ForgotPassword.Title", resourceCulture);
            }
        }
        
        internal static string ForgotPassword_Button {
            get {
                return ResourceManager.GetString("ForgotPassword.Button", resourceCulture);
            }
        }
        
        internal static string ForgotPassword_DontHaveAccount {
            get {
                return ResourceManager.GetString("ForgotPassword.DontHaveAccount", resourceCulture);
            }
        }
        
        internal static string ForgotPassword_Login {
            get {
                return ResourceManager.GetString("ForgotPassword.Login", resourceCulture);
            }
        }
    }
}
