//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenStore.Omnichannel.Identity.Resources.Views.Account {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Login_tr_TR {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Login_tr_TR() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("OpenStore.Omnichannel.Identity.Resources.Views.Account.Login_tr_TR", typeof(Login_tr_TR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Login_Title {
            get {
                return ResourceManager.GetString("Login.Title", resourceCulture);
            }
        }
        
        internal static string Login_SubTitle {
            get {
                return ResourceManager.GetString("Login.SubTitle", resourceCulture);
            }
        }
        
        internal static string Login_UserName {
            get {
                return ResourceManager.GetString("Login.UserName", resourceCulture);
            }
        }
        
        internal static string Login_Password {
            get {
                return ResourceManager.GetString("Login.Password", resourceCulture);
            }
        }
        
        internal static string Login_ForgetPassword {
            get {
                return ResourceManager.GetString("Login.ForgetPassword", resourceCulture);
            }
        }
        
        internal static string Login_Button {
            get {
                return ResourceManager.GetString("Login.Button", resourceCulture);
            }
        }
        
        internal static string Login_SignUp {
            get {
                return ResourceManager.GetString("Login.SignUp", resourceCulture);
            }
        }
        
        internal static string Login_DontHaveAccount {
            get {
                return ResourceManager.GetString("Login.DontHaveAccount", resourceCulture);
            }
        }
    }
}
