//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenStore.Omnichannel.Identity.Resources.Views.Account {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Register_tr_TR {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Register_tr_TR() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("OpenStore.Omnichannel.Identity.Resources.Views.Account.Register_tr_TR", typeof(Register_tr_TR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Register_Title {
            get {
                return ResourceManager.GetString("Register.Title", resourceCulture);
            }
        }
        
        internal static string Register_Description {
            get {
                return ResourceManager.GetString("Register.Description", resourceCulture);
            }
        }
        
        internal static string Register_Firstname {
            get {
                return ResourceManager.GetString("Register.Firstname", resourceCulture);
            }
        }
        
        internal static string Register_Surname {
            get {
                return ResourceManager.GetString("Register.Surname", resourceCulture);
            }
        }
        
        internal static string Register_Email {
            get {
                return ResourceManager.GetString("Register.Email", resourceCulture);
            }
        }
        
        internal static string Register_Password {
            get {
                return ResourceManager.GetString("Register.Password", resourceCulture);
            }
        }
        
        internal static string Register_ConfirmPassword {
            get {
                return ResourceManager.GetString("Register.ConfirmPassword", resourceCulture);
            }
        }
        
        internal static string Register_Button {
            get {
                return ResourceManager.GetString("Register.Button", resourceCulture);
            }
        }
        
        internal static string Register_Login {
            get {
                return ResourceManager.GetString("Register.Login", resourceCulture);
            }
        }
        
        internal static string Register_DoHaveAccount {
            get {
                return ResourceManager.GetString("Register.DoHaveAccount", resourceCulture);
            }
        }
        
        internal static string Register_PrivacyPolicyMustBeAgree {
            get {
                return ResourceManager.GetString("Register.PrivacyPolicyMustBeAgree", resourceCulture);
            }
        }
        
        internal static string Register_PrivacyPolicyLink {
            get {
                return ResourceManager.GetString("Register.PrivacyPolicyLink", resourceCulture);
            }
        }
        
        internal static string Register_PolicyReadAndApprove {
            get {
                return ResourceManager.GetString("Register.PolicyReadAndApprove", resourceCulture);
            }
        }
    }
}
