//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenStore.Omnichannel.Panel.Resources.Shared {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppNavMenu_tr_TR {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppNavMenu_tr_TR() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("OpenStore.Omnichannel.Panel.Resources.Shared.AppNavMenu_tr_TR", typeof(AppNavMenu_tr_TR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string MenuHeader_Channels {
            get {
                return ResourceManager.GetString("MenuHeader.Channels", resourceCulture);
            }
        }
        
        internal static string Menu_Home {
            get {
                return ResourceManager.GetString("Menu.Home", resourceCulture);
            }
        }
        
        internal static string Menu_Orders {
            get {
                return ResourceManager.GetString("Menu.Orders", resourceCulture);
            }
        }
        
        internal static string Menu_Products {
            get {
                return ResourceManager.GetString("Menu.Products", resourceCulture);
            }
        }
        
        internal static string Menu_AllProducts {
            get {
                return ResourceManager.GetString("Menu.AllProducts", resourceCulture);
            }
        }
        
        internal static string Menu_Inventory {
            get {
                return ResourceManager.GetString("Menu.Inventory", resourceCulture);
            }
        }
        
        internal static string Menu_Collections {
            get {
                return ResourceManager.GetString("Menu.Collections", resourceCulture);
            }
        }
        
        internal static string Menu_Customers {
            get {
                return ResourceManager.GetString("Menu.Customers", resourceCulture);
            }
        }
        
        internal static string Menu_Analytics {
            get {
                return ResourceManager.GetString("Menu.Analytics", resourceCulture);
            }
        }
        
        internal static string Menu_Documentation {
            get {
                return ResourceManager.GetString("Menu.Documentation", resourceCulture);
            }
        }
        
        internal static string Menu_Channels {
            get {
                return ResourceManager.GetString("Menu.Channels", resourceCulture);
            }
        }
        
        internal static string Menu_OnlineStore {
            get {
                return ResourceManager.GetString("Menu.OnlineStore", resourceCulture);
            }
        }
        
        internal static string Menu_Discounts {
            get {
                return ResourceManager.GetString("Menu.Discounts", resourceCulture);
            }
        }
        
        internal static string Menu_OnlineStore_Preferences {
            get {
                return ResourceManager.GetString("Menu.OnlineStore.Preferences", resourceCulture);
            }
        }
        
        internal static string Menu_OnlineStore_Theme {
            get {
                return ResourceManager.GetString("Menu.OnlineStore.Theme", resourceCulture);
            }
        }
        
        internal static string Menu_OnlineStore_BlogPosts {
            get {
                return ResourceManager.GetString("Menu.OnlineStore.BlogPosts", resourceCulture);
            }
        }
        
        internal static string Menu_OnlineStore_Pages {
            get {
                return ResourceManager.GetString("Menu.OnlineStore.Pages", resourceCulture);
            }
        }
        
        internal static string Menu_OnlineStore_Navigation {
            get {
                return ResourceManager.GetString("Menu.OnlineStore.Navigation", resourceCulture);
            }
        }
    }
}
